### ISSUE TITLE
Neue Regionen: Ulm/Neu-Ulm

### ISSUE THREAD

**Issue by stupps** [osmberlin/osm-parking-processing#102]
Hallo zusammen,
wir haben angefangen in Neu-Ulm und Ulm den Parkraum zu mappen. Könnt ihr uns mit aufnehmen?

Ulm: https://www.openstreetmap.org/relation/62495
Neu-Ulm: https://www.openstreetmap.org/relation/941087

Noch ist es nicht so viel, aber wir arbeiten dran :)

**Comment by gislars** [comment]
Prima, eine weitere Stadt kommt hinzu. Neu-Ulm und Ulm sind jetzt auch auf unserer Website gelistet. Viel Spaß beim Mappen!
