### ISSUE TITLE
Neue Region: Hattingen, NRW

### ISSUE THREAD

**Issue by PattaFeuFeu** [osmberlin/osm-parking-processing#103]
Moin!

Ich habe vor kurzem und in sehr kleinen Schritten angefangen, Hattingen zu mappen und würde mich freuen, wenn ihr die Stadt hinzufügen könntet.

Vielleicht fühlen sich durch die Verlinkung ja auch andere angespornt, mitzuhelfen. Bisher bin ich leider nicht lokal vernetzt.

Relation: https://www.openstreetmap.org/relation/162828

Viele Grüße!

P.S.: Vielleicht wäre es mit steigender Anzahl sinnvoll, die Regionen auf der Website noch mal zu unterteilen? Zum Beispiel nach Bundesländern und ggf. auch nach größeren Regionen (z. B. NRW—Ruhrgebiet—Hattingen)

**Comment by gislars** [comment]
Done. Die Statistiken sind nicht möglich, da braucht es in Zukunft eine flexiblere Lösung um auch verschiedene admin_level zu unterstützen. Die Karte zeigt die verarbeiteten Daten für das gesamte Gebiet an. https://parkraum.osm-verkehrswende.org/regions/hattingen/

**Comment by PattaFeuFeu** [comment]
Top, danke!

> Die Statistiken sind nicht möglich, da braucht es in Zukunft eine flexiblere Lösung um auch verschiedene admin_level zu unterstützen.

Wie habt ihr das denn bei anderen Städten gelöst?

**Comment by gislars** [comment]
Es wird strikt nach admin_level 4,9,10 gefiltert, bedingt durch den Start mit Berlin. Erst als kleinere Regionen dazukamen, funktionierte das nicht mehr, im Ausland bräuchte man auch eine andere Methode.
