### ISSUE TITLE
Liste der Regionen plötzlich deutlich verkürzt

### ISSUE THREAD

**Issue by PattaFeuFeu** [osmberlin/osm-parking-processing#104]
Moin!

Mir ist gestern aufgefallen, dass die Liste der Regionen inzwischen deutlich kürzer ist als noch vor wenigen Wochen, als ich zuletzt geguckt habe. #103 zum Beispiel ist nicht mehr aufzufinden, aber auch #102 und andere sehe ich nicht mehr. Der Link aus meiner Browserhistorie – https://parkraum.osm-verkehrswende.org/regions/hattingen/ – endet in einem 404-Fehler.

Auf der gerenderten Karte ist Hattingen aber noch erkennbar und die Daten werden augenscheinlich auch aktualisiert, denn ich kann letzte Änderungen von vor Kurzem dort sehen.

**Comment by tordans** [comment]
Hallo! Ja, wir haben diese Woche leider die Seiten von ein paar Regionen gelöscht. Ich werde das sehr bald korrigieren.

**Comment by tordans** [comment]
@PattaFeuFeu sorry für den Bug. Aber es freut mich zu hören, dass die Seite genutzt wird :-).
Erzähl uns gerne bei Gelegenheit, wie ihr die Daten nutzt und erfasst.

Die Regionen sind jetzt wiederhergestellt https://parkraum.osm-verkehrswende.org/regions/hattingen/
