### ISSUE TITLE
Keep a reference to separately mapped geometries in the data

### ISSUE THREAD

**Issue by tordans** [osmberlin/osm-parking-processing#13]
Our script already processes separately mapped parking areas next to the street. That is great!

However, after the processing, we loose the reference to the original area in our data.

Example: 
- separate area https://www.openstreetmap.org/way/554926168
- processed data https://parkraum.osm-verkehrswende.org/project-vector-tiles/#17.13/52.498818/13.434084
  - the processed data reference the street https://www.openstreetmap.org/way/100832885#map=16/52.4972/13.4385
  - the data is presented as `parking=street_side`, which is correct

Possible solutions:
- add a `data_source_osm_id` that holds the ID of the original data provider (street or area)
- ?

**Comment by gislars** [comment]
- die way_id wird bereits mitgeführt, bei highways ist immer ein way, keine area
- bei zerschnittenen Straßengeometrien wird ein Punkt/Komma und eine zusätzliche Ziffer angehängt
- bei abgeleiteten parking_lanes z.B. aus separat gemappten Parkflächen, sollte auch die OSM-ID der Parkfläche/Bus/Tram-Haltestelle usw. erhalten bleiben
- einige der letztgenannten IDs gehen durch das Zusammenfassen verloren
- die IDs können in einem zusätzlichen Arbeitsschritt wieder hinzugefügt werden

**Comment by tordans** [comment]
Der [Debug Layer in Kombination mit dem Layer Flächenparkplätze inkl. Parkbuchten](https://radverkehrsatlas.de/regionen/parkraum?lat=52.49&lng=13.4198&zoom=16.3&theme=parking&bg=default&config=!(i~parking~topics~!(i~parking~a~_F~s~!(i~default~a)(i~presence~a~_F)(i~surface~a~_F))(i~parkingPoints~a~_F~s~!(i~default~a))(i~parkingAreas~a~~s~!(i~default~a~_F)(i~position-separate~a))(i~parkingDebug~a~~s~!(i~default~a))(i~parkingStats~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*4~a~_F)(i~*9~a)(i~*10~a~_F)))(i~length~a~_F~f~!(i~admin*_level~o~!(i~*4~a~_F)(i~*9~a)(i~*10~a~_F))))(i~landuse~a~_F~s~!(i~default~a)))~) ist ausreichend. Ich schließe das Ticket.
