### ISSUE TITLE
Artefakte in der Kreuzung

### ISSUE THREAD

**Issue by tordans** [osmberlin/osm-parking-processing#20]
Beispiel: http://localhost:3000/project-vector-tiles#17.93/52.4813/13.437814

<img width="597" alt="image" src="https://user-images.githubusercontent.com/111561/175499232-1a038fe0-0db2-4930-89e0-406fc58338ef.png">

Die kleinen Stücke in der Mitte sollten wir irgendwann noch bereinigen.

**Comment by SupaplexOSM** [comment]
Am Ende sollten wir ohnehin alle Stücke ausschließen, die zu kurz für ein Fahrzeug sind. Das wäre hier der Fall. Möglicherweise müssen wir vorher das "merging"/Verschmelzen von Parkstreifen mit gleichen Eigenschaften optimieren.

**Comment by joshinils** [comment]
logisch gesehen weiß osm nicht, dass dort eine kreuzung ist, oder?
ansonsten muss man sich das irgendwie aus den daten dazu dichten.

also abstand zwischen kreuzungspunkten zu eng, also mit oneway separat gemapte fahrtrichtungen, ohne einbahnstraßenschild (sonst dürfte man ja innen am bordstein parken).

wenn ein bordstein gemapt wäre, kann man den abstand dazu ermitteln, der fehlt im kreuzungsbereich, also kann man dort nicht parken.
genauso sollte ein separater fußweg nicht mit footway=sidewalk sondern footway=crossing sein, also ist es eine kreuzung, also darf man nicht parken

**Comment by SupaplexOSM** [comment]
Im Script werden die Bordsteinschnittpunkte aus der (interpolierten) Straßenbreite interpoliert. Um Umkreis von 5 Metern um so einen Schnittpunkt wird alles abgeschnitten. Es wäre zusätzlich möglich, "virtuelle Kreuzungsflächen" aus den Flächen der Straßen selbst zu interpolieren. In meinem Neukölln-Prototyp hätte das aber nur vereinzelt einen Mehrwert gebracht.

Zusätzlich könnten wir auch Segmente innerhalb von [in OSM separat gemappten Knotenpunktflächen](https://www.openstreetmap.org/way/980716297) (`area:highway=*` + `junction=yes`) ausschließen, aber sowas gibt es bisher nur sehr selten.

**Comment by gislars** [comment]
Ich fürchte das Problem ist doch etwas aufwendiger zu lösen. Auch ich denke in die Richtung eine "Kreuzungsfläche" zu erzeugen und habe schon Experimente gemacht. 
Bisher habe ich versucht, nach dem Berechnen und Versetzen der parking_lanes, die Schnipsel zu entfernen. Aber so eine Kreuzung kann recht komplex sein.

Inzwischen denke ich, die Straßenlinie (highway=*) bei Kreuzungen zuerst zu kürzen und dann alle Berechnungen und weitere Verschneidungen zu machen.
Schnipsel mit einer Länge <1.7m werden bereits entfernt. 

Ein Beispiel einer Kreuzung
![Bildschirmfoto vom 2022-06-25 12-41-20](https://user-images.githubusercontent.com/402166/175770238-916388f9-d30e-4f82-bc2a-d37952fe7fc1.png)

- die gelben kurzen Strecken sollen entfernt werden
- die Kreise sind berechnete Puffer die zum ausstanzen benutzt werden
- der rosa Puffer der highway-Linie ist 2m dick und entfernt bereits viele Reststücke. Den Puffer kann ich aber nicht beliebig dick machen, bzw. müsste auch individuell für jede Kreuzung die Dicke bestimmen
- der orange Kreis wird nicht zum ausstanzen benutzt. Das ist ein 10m Radius um den Kreuzungsmittelpunkt. 
  - der Radius müsste an jede Kreuzung angepasst werden
  - eine Kreisform ist für viele Kreuzungen nicht gut geeignet
  - im vorliegenden Beispiel würden nur 3 der 4 Schnipsel vollständig entfernt
- die blau gestrichelte Linie zeigt die gemappte Kreuzungsfläche (junction=yes)
  - zum Entfernen der Schnipsel als letzter Schritt nicht geeignet 
  - könnte geeignet sein, wenn die highway-Linie vor allen Verarbeitungsschritten abgeschnitten wird
  - kaum gemappt (außer in NK) [Overpass-Link](https://overpass-turbo.eu/s/1jDl)
  - Fläche sollte aus den Daten abgeleitet werden können, evtl. eine vereinfachte Version
  - es gibt sehr unterschiedliche Kreuzungen, Reststücke entstehen nicht nur an Kreuzungen

**Comment by SupaplexOSM** [comment]
Das mit dem "Vor-Kürzen" ist eine gute Idee. Das würde das Problem hier und an ähnlichen Stellen lösen. Bei Kreuzungen mit scharfen Winkeln und breiten Straßen könnten dadurch aber evtl. neue Fehler entstehen. Müssten wir mal prüfen, welche Variante die "weniger schlimme ist" :)

Ein Ausschluss im Kreuzungsbereich - entweder über den orangenen Kreis (Durchmesser = schmalste zulaufende Straßenbreite) oder eine virtuelle Kreuzungsfläche entsprechend der zulaufenden Straßenbreiten) ist darüber hinaus nützlich, denke ich. Wenn alle Segmente mit capacity < 1 entfernt werden (statt pauschal nach Länge zu gehen), dürfte das Problem eigentlich auch weitgehend gelöst sein, oder? (In meinem Phython-Prototyp-Script gehe ich afaik so vor und habe kaum Probleme mit den Artefakten). Sehr seltenen Ausnahmen könnten beim Querparken entstehen, wo bereits ein 1,8-Meter-breites Segment eine capacity von 1 aufweist.

**Comment by gislars** [comment]
Vielen Dank! Klar wenn es keine capacity gibt, braucht es auch nicht angezeigt werden. Ich habe mir mal alle mit capacity = NULL eingeblendet und Stichproben gemacht. Die können wirklich ausgefiltert werden.

**Comment by gislars** [comment]
Ich benutze nun gekürzte highways. Es wird ein 5m-Puffer um jede highway-Kreuzung erzeugt und die highway-Linien darin ausgestanzt.

Das funktioniert gut bei einer Kreuzung mit 4 Segmenten. Bei einer "T-Kreuzung" mit 3 Segmenten, sollten nicht alle Segmente gekürzt werden.

Außerdem gibt es immer noch Artefakte [hier](https://parkraum.osm-verkehrswende.org/project-vector-tiles/#18.14/52.471345/13.452119) oder 
![Bildschirmfoto vom 2022-06-26 15-28-50](https://user-images.githubusercontent.com/402166/175818579-8fb3ee13-5b78-4c69-9b3b-2e3b0865773c.png)
 [hier](https://parkraum.osm-verkehrswende.org/project-vector-tiles/#16.93/52.544575/13.412813). Hier ist also noch weitere Arbeit notwendig.

**Comment by tifa365** [comment]
In der [Seligstraße](https://parkraum.osm-verkehrswende.org/project-vector-tiles/#16.58/52.514877/13.291785) in Charlottenburg befinden sich auch noch zwei, wobei die capacity als 16 angezeigt wird. Liegt vermutlich auch an der Ausstanzung?

**Comment by SupaplexOSM** [comment]
Ich habe gerade nochmal nachgeschaut, wie es im [Pythonscript](https://github.com/SupaplexOSM/street_parking.py/blob/main/street_parking.py) gelöst ist und da gibt es zwei Varianten:

- eine einfache, auskommentierte Variante, die den Kreuzungspunkt buffert und wegschneidet (was zu Problemen bei Kreuzungen mit "steilen Winkeln" oder sehr unterschiedlichen Straßenbreiten führen kann).
- eine langsamere, aber dafür sichere Variante, die alle Straßen entsprechend ihrer Breite (mit leichtem Abzug) buffert und dann alle von der Straßenlinie abgeleiteten Parkstreifen innerhalb dieser "Hülle" entfernt. Die "korrekten" Parkstreifen bleiben davon unberührt, weil die Hülle etwas kleiner ist als der Offset, mit dem die Parkstreifen vorher verschoben wurden. Funktioniert super :)

**Comment by tordans** [comment]
Lars hat die letzten Tage einiges verbessert. Ich habe mir [meinen Case](https://radverkehrsatlas.de/regionen/parkraum?lat=52.48126&lng=13.4376&zoom=17.9&theme=parking&bg=default&config=!(i~parking~topics~!(i~parking~a~~s~!(i~default~a)(i~presence~a~_F)(i~raw~a~_F))(i~parkingPoints~a~_F~s~!(i~default~a))(i~parkingAreas~a~~s~!(i~default~a)(i~position-separate~a~_F))(i~parkingDebug~a~_F~s~!(i~default~a))(i~parkingStats~a~_F~s~!(i~default~a~~filters~!(i~admin*_level~o~!(i~*4~a~_F)(i~*9~a)(i~*10~a~_F)))(i~length~a~_F~filters~!(i~admin*_level~o~!(i~*4~a~_F)(i~*9~a)(i~*10~a~_F))))(i~landuse~a~_F~s~!(i~default~a))(i~mapillaryCoverage~a~_F~s~!(i~default~a)))~) nochmal angeschaut und das sieht jetzt super aus.

Ich schließe das Ticket jetzt hier; bitte macht ein neues Ticket auf, wenn euch wieder etwas auffällt.
