### ISSUE TITLE
show age of data

### ISSUE THREAD

**Issue by joshinils** [osmberlin/osm-parking-processing#23]
maybe next to the copyright notice at the bottom as an iso8601 string?

**Comment by tordans** [comment]
Agreed. Also ping to https://github.com/gislars/strassenraum-berlin/issues/12.

**Comment by gislars** [comment]
Ich mache mal einen Versuch. An die Tabellen `boundaries_stats`, `parking_segments`, `parking_spaces`, `highways` schreibe ich per SQL-Comment den Timestamp der aus dem Import-File gelesen wird. In der Datei [$layer-name.json](https://vts.mapwebbing.eu/public.highways.json) ist das als `description` enthalten. Das kann auch vom front end ausgelesen und dann an einer beliebigen Position angezeigt werden.

Ich weiß noch nicht ob das so optimal ist. Zumindest hat man damit die Chance das Datum der Daten zu erfahren.

**Comment by tordans** [comment]
Unter https://parkraum.osm-verkehrswende.org/project-vector-tiles/dashboard zeige ich jetzt schonmal ein Datum an. Daraus kann man noch mehr machen… später.

**Comment by joshinils** [comment]
> Stand der Daten: Do 1.1.1237

bischen alt, aber ok ^^

am liebsten auch mit uhrzeit

**Comment by tordans** [comment]
> am liebsten auch mit uhrzeit

Hatte ich kürzlich mal gemacht…

**Comment by gislars** [comment]
in den letzten zwei Wochen habe ich noch ein paar Fehler behoben. Die letzten beiden Tage lief das Update ohne Fehler durch.

Übrigens, wenn auf der Webseite irgendwas mit "...NaN..." steht, ist ein laufendes Update ein Grund dafür.

**Comment by joshinils** [comment]
hm, das letzte update war stand jetzt (Mo 8. Aug 02:49:39 CEST 2022):
Stand der Daten: Sa 6.8.2022, 22:21:44

**Comment by gislars** [comment]
Die Updates werden vom Server der [Geofabrik](https://download.geofabrik.de/europe/germany/berlin.html#) geladen. Diese werden zu unterschiedlichen Zeiten fertig, sieht man wenn man auf "raw directory index" klickt. Der Stand der Daten und der Zeitpunkt ab wann die Extrakte zum Download zur Verfügung stehen unterscheidet sich. 
Ich habe  das Update auf kurz vor 6 Uhr morgens verschoben um die Chance zu erhöhen die Daten des aktuellsten Updates zu bekommen.

Ich habe leider keinen Mirror gefunden, der auch stündliche Updates für Berlin anbietet. Aus Frankreich gibt es stündliche Updates für Deutschland. Das wäre ein Weg für aktuellere Parkraumdaten oder versuchen die Updates aus den osm-changesets sich selbst zusammenbasteln.

**Comment by joshinils** [comment]
Hm, also ich würde dann eher was bauen das nachschaut ob neue daten verfügbar sind und die dann benutzt.
Also naiv: nachschauen jede stunde, wenn neue daten da sind diese verarbeiten und zeitpunkt merken, sonst nichts tun.

**Comment by tordans** [comment]
Unter https://parkraum.osm-verkehrswende.org/regions/berlin/ steht das Datum. Im Atlas steht es noch nicht, weil ich dafür Dinge umbauen müsste, wofür ich mir keine Zeit nehmen möchte. Ich denke, die Website reicht fürs erste.
