### ISSUE TITLE
Link to specific parking lane segment

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/osm-parking-processing#27]
Wäre es ein sinnvolles/umsetzbares Feature, auf ein Segment verlinken zu können? (via #4)

**Comment by tordans** [comment]
Ja, technisch machbar; aber nicht mal eben schnell. 

Und wir kommen gerade sehr schnell an die Grenzen der Fähigkeiten unserer Technologie (Jekyll mit etwas JavaScript direkt im HTML). Wenn wir mehr solche Feature haben wollen (was ich mir gut vorstellen kann), sollten wir auf Gatsby (React) wechseln.

**Comment by SupaplexOSM** [comment]
Nur um es irgendwo erwähnt zu haben: Genial wäre auch, den aktuellen Hintergrundlayer mit zu verlinken.

**Comment by tordans** [comment]
Mit dem Atlas gelöst.
