### ISSUE TITLE
Vector tile layer für addierte Kapazität

### ISSUE THREAD

**Issue by tordans** [osmberlin/osm-parking-processing#37]
Unter https://strassenraumkarte.osm-berlin.org/?map=parkingmap#18/52.47372/13.44154 gibt es diese gestrichelten Linien, die eine addierte Kapazität pro Straßensegment darstellen.

Diese würde ich gerne in dem Standard-Stil mit aufnehmen (siehe https://github.com/gislars/strassenraum-berlin/issues/16#issuecomment-1166347531).

Ich gehe davon aus, dass wir dafür einen neuen Vector tile layer bauen müssen, der die Daten aggregiert. Den Offset können wir im Styling angeben, solange die Linienrichtung richtig ist.

**Comment by gislars** [comment]
Das ist ein erster Entwurf für so einen Layer: https://vts.mapwebbing.eu/public.parking_summary.html

Straßensegmente sind zusammengefasst und die capacity wird pro Straßenseite summiert. Das ist alles noch WIP, es kommen noch Doppelungen vor, im Attribut capacity_string sind die Einzelwerte aufgelistet.

**Comment by joshinils** [comment]
https://www.openstreetmap.org/way/659928150 hat keine linie auf der linken seite
![image](https://user-images.githubusercontent.com/34302971/190681728-0dac1a10-8b3f-41b6-8558-06f1665138a8.png)

**Comment by joshinils** [comment]
https://www.openstreetmap.org/way/68196202 hat gar keine linien
![image](https://user-images.githubusercontent.com/34302971/190682071-7f3ca633-5be0-4889-8374-09190c9ce9db.png)

**Comment by joshinils** [comment]
außerdem gibt es noch keine aussparungen an kreuzungen;
![image](https://user-images.githubusercontent.com/34302971/190682264-e4774607-f19a-4fe8-a060-30c659430ac4.png)

**Comment by tordans** [comment]
Man kann im Atlas jetzt addieren.
