### ISSUE TITLE
Vector tile Layer für Punkte an Auto-Parkstellen

### ISSUE THREAD

**Issue by tordans** [osmberlin/osm-parking-processing#38]
Wir haben für https://github.com/gislars/strassenraum-berlin/issues/16#issuecomment-1166347531 versucht mit der Mapbox vector style specification die Rechtecke für parkende Autos zu platzieren. Das geht leider nicht gut.

Alex hat das für https://strassenraumkarte.osm-berlin.org/?map=parkingmap#18/52.47872/13.44238 so gelöst, dass er über spezielle Formeln (je nach Ausrichtung) Punkte auf der Linie verteilt, die er dann nutzt um jew. ein Icon dort zu platzieren.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/111561/177944510-d39b7e95-973c-46a9-8de0-a4b4efdb5e4f.png">

Einen solchen Layer bräuchten wir auch, um die Vector Tiles so hübsch zu machen, wie die von Alex.

**Comment by gislars** [comment]
Es gibt einen neuen Vector Tile layer: https://vts.mapwebbing.eu/public.parking_spaces.html

Features/Probleme:
- nur bei großen Zoomlevel (>= 17) anzeigen, Browser kann sonst crashen
- zeigt einen Punkt pro Stellplatz
- enthält Attribut `angle`, das könnte beim Styling nützlich sein um ein Rechteck zu drehen
  - der Winkel hängt von der Ausrichtung (Start -> Ende) der Straßengeometrie ab
  - da nicht alle Straßen gleich ausgerichtet sind, müssten ggf. + 180 ° addiert werden
  - bei gebogenen Straßengeometrien, ist der Winkel nicht verlässlich
- auch bei Fahrradstellplätzen auf der Straße werden im Moment die Punkte berechnet 
- die Anzahl der Punkte wird auf Basis der `capacity` bestimmt

Anbei zwei Screenshots aus QGis
![Bildschirmfoto vom 2022-07-09 01-36-06](https://user-images.githubusercontent.com/402166/178082210-c5b4e82f-d8e4-4788-949b-35f9a5eef22e.png)
![Bildschirmfoto vom 2022-07-09 01-38-46](https://user-images.githubusercontent.com/402166/178082335-b4b5d0f4-4e38-4ac1-8367-577a70adfd80.png)

**Comment by joshinils** [comment]
> Es gibt einen neuen Vector Tile layer: https://vts.mapwebbing.eu/public.parking_spaces.html

Probleme sehe ich in Frohnau auch in der Dichte der Punkte.
Manchmal sind die Punkte so nah aneinander, dass sie aussehen wie eine durchgehende Linie, woran kann das liegen?

zb. https://www.openstreetmap.org/way/1075776393 hat sehr viele, 
![image](https://user-images.githubusercontent.com/34302971/178096932-2bcf69ad-35c3-4ebb-8b93-e7799020f0e8.png)

auch https://parkraum.osm-verkehrswende.org/project-vector-tiles/#17.58/52.633632/13.288011 zeigt dort eine 9 auf einem sehr kleinen segment:
![image](https://user-images.githubusercontent.com/34302971/178096921-5e15041b-dd5d-4fa3-9bbf-50a98ad4f148.png)

**Comment by SupaplexOSM** [comment]
Die zu engen Punkte an manchen Segmenten sind eine Folge von #30 (bzw. im Fall von Fahrradständern auf der Fahrbahn liegt es daran, dass die Fahrradständer zur Zeit als eine Sonderform von "Parkstreifen" mit der capacity des Fahrradständers dargestellt/interpretiert werden).

Für ein organisches Rendering müsste sich jeder Punkt den Winkel "seiner" (versetzten) Linie an seinem Ort holen. Für das Rendering der Straßenraumkarte entsteht dieser Winkel als Nebenprodukt des "Points along Lines"-Algorithmus.

**Comment by tordans** [comment]
Das Thema ist jetzt schön gelößt.
