### ISSUE TITLE
Umgang mit parking:lane "marked" oder "painted_area_only"

### ISSUE THREAD

**Issue by joshinils** [osmberlin/osm-parking-processing#42]
das `highway=living_street` oder `trafic_sign=DE:325.1` impliziert (hier wichtig) folgendes:
haltverbot `parking:condition:<both>=no_parking`
mit ausnahme von markierten bereichen; [`parking:lane:<side>=marked`](https://wiki.openstreetmap.org/wiki/Key:parking:lane#Parking_type) bzw. [`parking:lane:<side>:<type>=painted_area_only`](https://wiki.openstreetmap.org/wiki/Key:parking:lane#parking:lane:side:type-painted_area_only)

**Comment by joshinils** [comment]
> . (Ja, man könnte annehmen, das das Spielstraßenschild ebenso als Verbot behandelt werden kann wie ein Halte-/Parkverbotszeichen, aber das wird mMn bereits durch das living_street an der Straßenlinie ausgedrückt und ist daher quasi implizit statt explizit. Ist wohl geschmackssache bzw. nicht klar definiert...)

ja genau das meine ich, dort kann man für die analyse annhemen, dass man nirgends parken darf, als standardwert. das scheint derzeit nicht der fall zu sein.

**Comment by SupaplexOSM** [comment]
Ach so meinst du das. Ich würde auf keinen Fall mit defaults arbeiten: Habe mir die living_streets in Neukölln und Umgebung mal angesehen und in den meisten sind Parkbereiche ausgewiesen.

**Comment by SupaplexOSM** [comment]
Ich schließe hier mal, da wir im Projekt eher darauf verzichten wollten, implizite Annahmen zu treffen (und wir gerade Tickets aufräumen ;). Also wenn für einen verkehrsberuhigten Bereich keine Daten erhoben wurden, dann sollte das so auch im Tool erkennbar sein, um sie ggf. zu ergänzen oder die explizite Abwesenheit von Parkplätzen zu ergänzen.

**Comment by joshinils** [comment]
naja, so ganz implizit ist das nicht.
in der StVO steht nunmal zu VZ 325.1:
> 4.
>    Wer ein Fahrzeug führt, darf außerhalb der dafür gekennzeichneten Flächen nicht parken, ausgenommen zum Ein- oder Aussteigen und zum Be- oder Entladen.

ich würde dem entnehmen, dass wenn es keine eingetragenen flächen gibt, es immer überall verboten ist in highway=living_street.

Das Zeichen 325.1 ist ein explizites eingeschränktes haltverbotsschild, quasi eine zone. 

wenn infos fehlen, darf man dort nicht parken

**Comment by SupaplexOSM** [comment]
Ich meine es eher so herum: Nur weil in OSM keine Parkflächen ausgewiesen sind, heißt es nicht, dass dort keine sind (denn wie weiter oben beschrieben: Erfahrungsgemäß sind in vielen Fällen welche vorhanden). Also für ein Projekt wie dieses hier wäre es besser, zu sehen, dass dort noch keine Informationen erfasst sind (egal ob Parken oder kein Parken) und diese Straßen also als "unbekannter Parkstatus" zu kennzeichnen als pauschal von "kein Parken" auszugehen, obwohl es so nicht explizit in den Daten steht.

**Comment by joshinils** [comment]
ja, mit unbekannt geh ich d'accord.
das ist ja was anderes als zu sagen da ist eigentlich immer was pauschal gesagt, wäre ja auch eine annahme.
