### ISSUE TITLE
Aerial images from Berlin for 2022 are available

### ISSUE THREAD

**Issue by tifa365** [osmberlin/osm-parking-processing#45]
Would be nice to add those as an exta layer as well.
https://fbinter.stadt-berlin.de/fb/berlin/service.jsp?id=a_luftbild2022_true_rgbi@senstadt&type=FEED

- [x] Im Editor
- [x] Auf der Webseite

**Comment by tordans** [comment]
Ist schon länger erledigt, daher jetzt auch mal geschlossen :)
