### ISSUE TITLE
Parkflächen außerhalb der Straße auswerten, darstellen

### ISSUE THREAD

**Issue by tordans** [osmberlin/osm-parking-processing#57]
Siehe https://twitter.com/Synchronisator/status/1588569129627295745

Alex stellt in https://parkraum.osm-verkehrswende.org/project-prototype-neukoelln/?map=parkingmap#18/52.47554/13.44729 die Flächen verschiedenen Parkraum-Daten außerhalb der Straße dar. Zlant in seinem Editor ebenfalls.

Wir könnten / sollten …
- Diese Daten prozessieren und als Vector Layer bereit stellen
- Als optionalen Zusatzlayer anzeigen und mit Legende erklären
- Langfristig: Dazu auch Berechnungen durchführen – aber für den Anfang würde allein eine visuelle Anzeige schonmal helfen
- Eine Doku erstellen in der wir auf die üblichen anderen Wiki-Artikel zum Thema + `access=private` verweisen, vor allem TG Einfahrten brauchen glaube ich eine explizite Doku https://twitter.com/tordans/status/1588770854711988225

**Comment by joshinils** [comment]
Streetcomplete stellt parkplätze in dem park-layer auch dar.

**Comment by SupaplexOSM** [comment]
Als Layer anzeigen (und später bei Bedarf mit Prozessieren) wäre auch meine Vorstellung gewesen.

Thema Tiefgaragenstellplätze: Diese sind - bis auf ihre Zufahrten - schwer "on the ground" verifizierbar. Für ein Projekt wie unseres ist das schade, denn nur mit Flächeninformationen könnte man capacities abschätzen. Flächeninfos zu Tiefgaragen kann man zwar aus ALKIS oder Beobachtungen vor Ort abschätzen, aber eben meist wirklich nur grob... (Daher habe ich Tiefgarageninfos für die Neuköllner Parkraumanalyse alle lokal außerhalb von OSM gepflegt).

Bin da noch etwas ratlos, ob/wie man diese Variable auf OSM-Basis integrieren könnte.

**Comment by tordans** [comment]
In unserer neuen, kommenden Ansicht der Karte werden Parkflächen außerhalb der Straße optional mit angezeigt. Die URL zu dieser Ansicht wird in 1-2 Wochen veröffentlicht. Ich schließe hier aber schonmal um aufzuräumen.
