### ISSUE TITLE
street furniture interfering with kerb parking

### ISSUE THREAD

**Issue by joshinils** [osmberlin/osm-parking-processing#58]
beispiel: https://www.openstreetmap.org/way/46672238
https://parkraum.osm-verkehrswende.org/project-vector-tiles/#18/52.478358/13.425814
https://parkraum.osm-verkehrswende.org/project-prototype-neukoelln/?map=parkingmap#18/52.47831/13.42586

da hat alex wohl manuell die parkplätze um die bäume herum geführt, sodass dort nur 16 plätze gelten, in dieser karte aber sind 16+8=24 verzeichnet.

ich nehm an, dass bäume, poller, straßenschilder, laternen, street_cabinet, fahrradständer, etc. pp noch nicht beachtet werden.

**Comment by SupaplexOSM** [comment]
Ja, die habe ich in der Neuköllner Analyse manuell einbezogen (also manuell die Auswahl der zu berücksichtigenden Objekte vorgenommen und diese dann mit bestimmten Radien entsprechend der Art des "Möbels" etc. ausgestanzt.)

Automatisiert ist das derzeit mMn noch nicht zuverlässig genug möglich, da die Genauigkeit der Daten selten ausreicht, um sagen zu können, ob sich ein Parkstreifen z.B. direkt _neben_ oder _zwischen_ einer Reihe von Straßenbäumen befindet. Hier (#56) habe ich bereits über ein Tagging wie `position=parking` nachgedacht, um Bäumen, Straßenmöbeln etc. ein entsprechendes Attribut mitzugeben. Das ist die einzige Lösung (außer Relationen), die mir bisher einfiel, auch wenn sie etwas hacky ist.

**Comment by joshinils** [comment]
hm, also müsste man alle "Straßenmöbel" entsprechend taggen, damit diese als korrekt berücksichtigt werden können...
theoretisch reicht ja deren Position aus, oder kann das irgendwann zu ungenau sein? ein [baum]( https://www.openstreetmap.org/node/9004598531) kann ja eine position und einen umfang haben, die position ist dann innerhalb eines separat erfassten [amenity=parking](https://www.openstreetmap.org/way/972914848). 
oder ich stell mir das zu einfach vor.
natürlich muss man all diese möbel dann erfasst haben, zumindest an stellen wo die im weg sein könnten, also überall wo separate parkflächen genutzt werden, und wo man halb oder ganz auf dem bordstein parken muss/darf. bäume zu verifizieren dauert ja schon lange mit meiner bisherigen vorgehensweise, aber _auch_ alle poller, straßenschilder, laternen etc. zu erfassen... da wird man nie fertig ohne deutlich mehr hilfe

**Comment by SupaplexOSM** [comment]
Achso, bei separaten Flächen ist das natürlich kein Problem. Aber ich bin jetzt vom "Standardfall" ausgegangen, dass die Parkstreifen als Attribut der Straßenlinie erfasst wurden. (In solchen Fällen immer separat zu mappen, wäre eine weitere Option, aber die wäre genauso hacky ;-)
Gezielt nach Straßenabschnitten mit Gehwegparken zu suchen und dort alle Objekte im Parkstreifenbereich zu mappen, fand ich mit unseren Bilderquellen in Berlin nicht besonders aufwendig. Ich habe in Neukölln nicht lange dafür gebraucht, das systematisch zu erfassen. Wenn ich irgendwo Gehwegparken sehe, mappe ich die Objekte meistens gleich mit. In anderen Städten ohne jährliche Luftbilder, freie Katasterdaten und Top Straßenfotos sieht das natürlich sowieso anders aus...

**Comment by SupaplexOSM** [comment]
Achso, bei separaten Flächen ist das natürlich kein Problem. Aber ich bin jetzt vom "Standardfall" ausgegangen, dass die Parkstreifen als Attribut der Straßenlinie erfasst wurden. (In solchen Fällen immer separat zu mappen, wäre eine weitere Option, aber die wäre genauso hacky ;-)
Gezielt nach Straßenabschnitten mit Gehwegparken zu suchen und dort alle Objekte im Parkstreifenbereich zu mappen, fand ich mit unseren Bilderquellen in Berlin nicht besonders aufwendig. Ich habe in Neukölln nicht lange dafür gebraucht, das systematisch zu erfassen. Wenn ich irgendwo Gehwegparken sehe, mappe ich die Objekte meistens gleich mit. In anderen Städten ohne jährliche Luftbilder, freie Katasterdaten und Top Straßenfotos sieht das natürlich sowieso anders aus...

**Comment by joshinils** [comment]
naja, in frohnau sieht man auf den luftbildern meist nur wald... um poller und ähnliches kleines zu mappen sind die nutzlos.
und die streetlevel-bilder sind meist schlecht verortet, sodaß man zwar die existenz der möbel feststellen kann, aber genau sagen wo die hin kommen geht auch schlecht finde ich.
und vor ort ist es auch nciht einfacher, da man nur die luftbilder als anhaltspunkte hat, wo man ja nix sehen kann.
bäume und laternen sind noch am einfachsten, dann kommen flurstücksgrenzen und bordsteine.

**Comment by SupaplexOSM** [comment]
Update: In Neukölln und Friedrichshain-Kreuzberg habe ich in den letzten Monaten konsequent den Tag `obstacle:parking=yes` verwendet, um Objekte im Bereich von Parkstreifen kenntlich zu machen. [`obstacle`](https://wiki.openstreetmap.org/wiki/Key:obstacle) ist ein bereits im Wiki vorgeschlagenes Konzept für "Hindernisse", die eher nicht in den `barrier`-Raum fallen, das insbesondere (undokumentiert, soweit ich sehe) im Barrierefreiheitskontext Verwendung zu finden scheint (`obstacle:wheelchair` und `obstacle:blind` haben etwas Verbreitung).

Ich habe es quasi für den Bereich Parken adaptiert: Ist eine Laterne o.ä. ein "Hindernis" beim Parken, kommt der Tag ran. Könnte theoretisch auch für Parkassistenzsysteme interessant sein... Das [Pythonscript](https://github.com/SupaplexOSM/street_parking.py/blob/main/street_parking.py) wertet den Tag bereits aus und erzielt damit zufriedenstellende Ergebnisse, sodass keine manuelle Nachbearbeitung mehr nötig ist.

**Comment by gislars** [comment]
obstacle habe ich eingebaut, ich teste das noch lokal und danach geht es online

#5

**Comment by joshinils** [comment]
gibt es eine wikiseite die all diese speziellen tags die wir benutzen auflistet?

**Comment by SupaplexOSM** [comment]
> gibt es eine wikiseite die all diese speziellen tags die wir benutzen auflistet?

Ich habe angefangen, eine [Wikiseite](https://wiki.openstreetmap.org/wiki/User:Supaplex030/Street_parking:_How_to_map_a) für einige dieser "speziellen" Tags einzurichten, aber würde gerne noch eine bessere Form finden, wie man das dokumentieren kann. Nicht nur eine eigene in-use-Wikiseite für Tags wie `obstacle:parking`, die ich bei Gelegenheit mal anlegen kann, sondern darüber hinaus eine übersichtlichere Form speziell für Menschen, die unsere Methode nutzen und "mal eben" nachsehen wollen, wie diese oder jede "Stanzung" erzielt werden kann. Bin immer offen für Ideen ;)

**Comment by tordans** [comment]
@SupaplexOSM gibt es für dieses Ticket noch ein nächstes TODO oder können wir es schließen?

**Comment by joshinils** [comment]
ich wünsche mir dokumentation des speziellen taggings für dieses *osbstacle* tag, bzw. dokumentation zu dem projekt allgemein, auch gern im berlin namensraum im osm wiki

**Comment by SupaplexOSM** [comment]
Ich hab mal die parkraumbezogene "How to map a..."-Seite in den Verkehrswende-Namensraum verschoben: https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/Parkraum/How_to_map_a

Welche Dokumentation wird denn darüber hinaus benötigt?

(Unabhängig davon würde ich hier dennoch schließen, da die Prozessierung zumindest mit entsprechend getaggten Straßenmöbeln umgehen kann.)
