### ISSUE TITLE
parking_poly: Support new schema for `orientation`

### ISSUE THREAD

**Issue by tordans** [osmberlin/osm-parking-processing#68]
## Test data

Old schema:
- https://www.openstreetmap.org/way/1077763105#map=19/52.53307/13.41464
- https://vts.mapwebbing.eu/processing.parking_poly.html#19/52.53307/13.414636

=> Is supported

New Schema:
- https://www.openstreetmap.org/way/1085484773#map=19/52.53470/13.40437
- https://vts.mapwebbing.eu/processing.parking_poly.html#18/52.534651/13.404222

=> Not supported

## Fix

- Either support both … or only the new schema

## Original isse:

              Hallo, ich bin dabei die Tags in Hannover zu updaten.
Dabei ist mir aufgefallen, dass bei einigen Flächen das Tag:
`
orientation = perpendicular
parking = street_side
`
statt
`
parking:orientation = perpendicular
parking = street_side
`
verwendet wird. Wie es scheint wird das dann nicht korrekt dargestellt.
Das sollte vllt auch berichtigt werden.

_Originally posted by @synchronisator in https://github.com/osmberlin/parkraum.osm-verkehrswende.org/issues/30#issuecomment-1473718318_

**Comment by synchronisator** [comment]
Als Hinweis:
vom iD-Editor wird nur `parking:orientation=perpendicular` unterstützt.

**Comment by gislars** [comment]
Das ist mir durchgerutscht, ich habe es gefixt, es ist aber noch nicht online. Bei den separat gemappten Flächen gibt es noch ein anderes Problem.
Da bei den anderen Tags auch nur das neue Schema unterstützt wird, habe ich mich in diesem Fall auch dafür entschieden. Flächen mit dem alten Schema werden dann nicht mehr berücksichtigt

**Comment by SupaplexOSM** [comment]
> vom iD-Editor wird nur `parking:orientation=perpendicular` unterstützt

Hatte @tordans dafür nicht schonmal einen pull request, um das in iD zu aktualisieren?

**Comment by gislars** [comment]
Änderung gemerged mit #74

**Comment by joshinils** [comment]
@SupaplexOSM die sind beide nicht in der overpass-query enthalten die nach alten tags sucht;
https://www.openstreetmap.org/user/Supaplex030/diary/401053

**Comment by tordans** [comment]
Unsere Prozessierung ist fertig. Den Status im iD Editor tracke ich in https://github.com/osmberlin/osm-parking-processing/issues/79
