### ISSUE TITLE
Anpassungen an neues `parking:lane` Schema

### ISSUE THREAD

**Issue by tordans** [osmberlin/osm-parking-processing#7]
Aktuell haben wir ein Misch-Tagging in Berlin. Die größten Teile (und ganz Neukölln) verwenden das alte `parking:lane` Schema.

Alles, was mit einer neueren Version des Zlant-Editors erfasst wurde dagegen nutzt das neue Schema. Die Auswirkungen sind aber überschaubar, da wir kaum Fragestellungen mappen, die das geänderte Tagging betreffen (wenig conditional).

In den nächsten Monaten sollen wir …
1. In Berlin das neue Schema ausrollen
2. Die Skripte anpassen

---

Eine Liste an Änderungen findet sich…
- Im Wiki
- Im Matrix Kanal

**Comment by gislars** [comment]
Hierzu sollten wir mal eine vorher-nachher-Übersicht machen

**Comment by SupaplexOSM** [comment]
Ich frage mich seit dem Proposal, ob unsere Scripte beide Varianten auswerten können sollten, also insbesondere wenn wir uns den conditions widmen. Mein Python-Script ist ja quasi in der alten Zeit geboren und kann damit umgehen, aber ich weiß nicht ob man das immer weiter mitschleifen muss. Vielleicht muss man halt erst dafür sorgen, dass alles in aktuellem Schema gemappt ist.

**Comment by tordans** [comment]
Ich votiere dafür, das neue Script nur auf dem neuen Schema aufbauen zu lassen.
Und parallel daran zu arbeiten, dass das alte Schema ausläuft. 
Wir sollten in OSM mehr Arbeit investieren ins Aufräumen (Chaos zu beseitigen), statt darein, Chaos zu managen. (Oder wie Wikinaut sagen würde: "den Zaun reparieren statt ständig die Hühner einzufangen.")

**Comment by tordans** [comment]
Ergänzung: Ich hatte auch schon vor, eine MapRoulette Challenge dafür zu machen; ich habe jetzt mal https://github.com/gislars/strassenraum-berlin/issues/26 angelegt um das zu tracken.

**Comment by tordans** [comment]
Wann können wir das Ticket schließen:

a. Wenn wir aktuell im neuen Script nur das neue Schema verwenden

und

b. Wenn wir übereinstimmen, dass wir nur das neue Schema verwenden

**Comment by SupaplexOSM** [comment]
a. und b. sind glaube ich nach aktuellem Stand erfüllt, daher schließe ich? ;)
