### ISSUE TITLE
Neue Region: Braunschweig

### ISSUE THREAD

**Issue by Eeevva** [osmberlin/osm-parking-processing#84]
Hi, könnt ihr Braunschweig ergänzen?
Die Relation ist: https://www.openstreetmap.org/relation/62531

**Comment by tordans** [comment]
@Eeevva auch die Statistik funktioniert jetzt. Du kannst also voll durchstarten!
Erzähl uns gerne bei Zeiten, wie es läuft…

**Comment by Eeevva** [comment]
Prima, danke!

**Comment by tordans** [comment]
@Eeevva bei der Prozessierung ist uns aufgefallen, dass es noch highway=road 1x bei euch gibt. Vielleicht kannst du das mal umtaggen bei Gelegenheit. Mehr unter https://maproulette.org/browse/challenges/39479

<img width="291" alt="image" src="https://github.com/osmberlin/osm-parking-processing/assets/111561/19a259b1-3005-4fed-a4fb-ecb3401a8dc9">
