### ISSUE TITLE
Neue Region: Freiburg

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/osm-parking-processing#95]
Mich hat jemand aus Freiburg kontaktiert, der dort Parkraumdaten für eine Abschlussarbeit sammelt. In einem Stadtteil ist schon alles flächendeckend erhoben. @gislars kannst du Freiburg in die Liste aufnehmen?

Hier die Relation: https://www.openstreetmap.org/relation/62768

**Comment by gislars** [comment]
Freiburg ist jetzt online: https://parkraum.osm-verkehrswende.org/regions/freiburg/
