### ISSUE TITLE
Umgang mit Bäumen

### ISSUE THREAD

**Issue by mathiasellpunkt** [osmberlin/osm-parking-processing#96]
Hallo in die Runde,

beim Erfassen der Altbauviertel in Wiesbaden kommen mir (zum Glück) recht viele Straßen unter die Feder, deren Parkstreifen durch Bäume unterbrochen sind. (Siehe Foto). Ich habe das nun gelöst, in dem ich den Parkraum separat kartiert habe (siehe Screenshot).

Zwei Fragen aber dazu:
(1) Wäre es möglich, die Bäume irgendwie automatisch zu berücksichtigen (analog Haltestellen und Kreuzungen)? 
(2) Wie bekomme ich die Parkplätze optisch gleich breit? :D

![IMG_20230920_155542](https://github.com/osmberlin/osm-parking-processing/assets/74745290/5a491a21-9419-42a5-9ece-4d6390accbec)

![grafik](https://github.com/osmberlin/osm-parking-processing/assets/74745290/9d512b76-10e6-4015-b075-497ac3c1f0f3)

**Comment by tordans** [comment]
Noch ein Hinweis zum Screenshot: Die Parkbuchten müssten eigentlich ein kleineres P haben. Schau nochmal, ob das Tagging hier vollständig ist.  Bspw. https://www.openstreetmap.org/way/839025964

```
access  yes
access	yes
amenity	parking
fee	no
orientation	parallel
parking	street_side
surface	sett
```

**Comment by mathiasellpunkt** [comment]
> Soweit ich weiß berücksichtigen wir dafür `obstacle:parking=yes` (laut #5 ist es schon eingebaut). Beispiel https://www.openstreetmap.org/node/1650912547
> 
> Allerdings sieht es für mich danach aus, dass die Bäume bei dir mit ihrer Baumscheibe zu großen Abstand haben, so dass hier das separate Mappen der Parkbuchten doch der bessere Weg ist.

Gut zu wissen. Ich teste das einfach mal bei der nächsten Straße.
 
> Du meinst die Breite im Screenshot von Nord-Süd, richtig? Vermutlich nur mit JOSM, mit iD gibt es dafür keine Lösung soweit ich weiß. Zur Erinnerung: in seinem Screenshot werden die Elemente überlagert von der Straße. Es kann also sein, dass es unterschiedlich "breit" ist, weil die Straße nicht ganz parallel zu den Parkplatzgeometrien läuft.

Genau, ich meine die (in dem Fall) Nord-Süd-Ausdehnung. Ich werde dann daheim mal den JOSM testen.

**Comment by joshinils** [comment]
> Genau, ich meine die (in dem Fall) Nord-Süd-Ausdehnung. Ich werde dann daheim mal den JOSM testen.

Ich mach das so, dass ich die geomtrie entweder einfach kopiere, oder eine art hilfsgitter baue.

beim kopieren wäre mnir persönlich jetzt wichtig, dass die alte geometrie nicht gelöscht und ersetzt wird. das geht in josm mit https://wiki.openstreetmap.org/wiki/JOSM/Plugins/utilsplugin2 und [ctrl+shift+G](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/utilsplugin2#Replace_geometry_(Ctrl+Shift+G))

bei dem hilfsgitter ziehe ich eine linie wie bei reihenhäusern, die die ganzen wie ein karogitter verbindet, danach kann ich alle verbundenen flächen selektieren und rechtwinklig machen, danach alle hilfslinien löschen.
![image](https://github.com/osmberlin/osm-parking-processing/assets/34302971/86f022e9-1bb9-47a6-8f0f-80bb4a9cf3e4)

im übrigen sollten diese flächen nicht mit den straßen-ways verbunden sein, die liegen zwar neben der fahrbahn, aber der way ist ja mittig der fahrbahn, und die flächen nicht. da muss also etwas platz sein.
vermutlich gibt es da keine perfekten luftbilder, da kann man also nur raten, oder andere hilfsmittel nehmen, die alle deutlich komplizierter sind

**Comment by mathiasellpunkt** [comment]
Aaah, ich habe die tatsächlich fest mit der Straße verbunden, weil ich dachte, das sei vielleicht irgendwann für ein Routing wichtig. Wenn die separat stehen, macht das das Copy&Paste einfacher.
