### ISSUE TITLE
Fehlerhafte Prozessierung beidseitiger Parkplätze

### ISSUE THREAD

**Issue by mathiasellpunkt** [osmberlin/osm-parking-processing#99]
Hallo in die Runde,

ich habe eine fehlerhafte Verarbeitung der Parkplätze der (nördlichen) Schiersteiner Straße in Wiesbaden festgestellt. Es handelt sich um eine Straße mit zwei getrennten Fahrbahnen, die jeweils (!) auf beiden Seiten der Fahrbahn parallele Parkplätze hat. Hier das Luftbild:

![grafik](https://github.com/osmberlin/osm-parking-processing/assets/74745290/a9830848-512e-4cd3-8612-d6c422f3355e)

Auch unter den Böumen finden sich Parkplätze, entsprechend aber weniger.

https://www.openstreetmap.org/way/1213424769

Die Parkdaten sind soweit ich das sehe korrekt eingestellt; hier der Screenshot aus StreetComplete sowie Beispielhaft die Tags eines Abschnitts:

![grafik](https://github.com/osmberlin/osm-parking-processing/assets/74745290/4c48a2b2-e87b-4873-8ea1-5643f07fa86b)

```
cycleway:right=no
highway=tertiary
lanes=1
lit=yes
maxspeed:type=DE:urban
name=Schiersteiner Straße
name:etymology:wikidata=Q478142
oneway=yes
parking:both=lane
parking:both:orientation=parallel
postal_code=65185
sidewalk=right
surface=asphalt
```

Dennoch werden die mittig liegenden Parkplätze nicht ermittelt - siehe hier:

![grafik](https://github.com/osmberlin/osm-parking-processing/assets/74745290/aed61621-9be9-4ba4-bf28-4524339a68d5)

Woran hängts?

**Comment by joshinils** [comment]
Da das echte Einbahnstraßen sind, mit Zeichen 220, darf man linksseitig parken, ja.
Dann trifft das `dual_carriageway=no` zu, das könnte man taggen, um das zu erkennen.
Trotzdem sollte das unabhängig vom tagging als Parkraum erfasst werden, finde ich.

Du känntest mal die `width` messen mit SC, die fehlt, ich kann mir vorstellen, dass sich deshalb die inneren Geometrien überlappen und deswegen gelöscht werden?

**Comment by joshinils** [comment]
Schaut bei mapillary so aus als hätte man den Grünstreifen, der nach dem Zebrastreifen kommt, entfernt und zu Parkplatz gemacht. 
Da abseits der Inseln nur eine aufgemalte Linie die Fahrbahnen (Fahrstreifen?) zu trennen scheint, weiß ich übrigens auch nicht, ob das in OSM korrekt abgebildet ist als zwei Linien, aber vielleicht am richtigsten gegenüber einer.

**Comment by SupaplexOSM** [comment]
> Du känntest mal die `width` messen mit SC, die fehlt, ich kann mir vorstellen, dass sich deshalb die inneren Geometrien überlappen und deswegen gelöscht werden?

Könnte ich mir auch vorstellen: Ergänze mal die Fahrbahnbreite als `width`. Laut Luftbild sind das 7 Meter (`width=7`) auf der südlichen Seite und 8 auf der nördlichen. Möglicherweise werden die Parkstreifen ansonsten zu weit/übereinander verschoben, weil Default-Werte für `tertiary` verwendet werden, die für diese Situation zu groß sind.

**Comment by mathiasellpunkt** [comment]
![grafik](https://github.com/osmberlin/osm-parking-processing/assets/74745290/028f1803-9b22-404e-a92e-606aa0586f85)

Schaut gut aus!

**Comment by mathiasellpunkt** [comment]
Closed :)
